// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: pkg/pb/inventory.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmptyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	mi := &file_pkg_pb_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_inventory_proto_rawDescGZIP(), []int{0}
}

type FindRecordsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindRecordsRequest) Reset() {
	*x = FindRecordsRequest{}
	mi := &file_pkg_pb_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRecordsRequest) ProtoMessage() {}

func (x *FindRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRecordsRequest.ProtoReflect.Descriptor instead.
func (*FindRecordsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *FindRecordsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *FindRecordsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type InventoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryResponse) Reset() {
	*x = InventoryResponse{}
	mi := &file_pkg_pb_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryResponse) ProtoMessage() {}

func (x *InventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryResponse.ProtoReflect.Descriptor instead.
func (*InventoryResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *InventoryResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InventoryResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type FindRecordsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*InventoryResponse   `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindRecordsResponse) Reset() {
	*x = FindRecordsResponse{}
	mi := &file_pkg_pb_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindRecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRecordsResponse) ProtoMessage() {}

func (x *FindRecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRecordsResponse.ProtoReflect.Descriptor instead.
func (*FindRecordsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *FindRecordsResponse) GetRecords() []*InventoryResponse {
	if x != nil {
		return x.Records
	}
	return nil
}

var File_pkg_pb_inventory_proto protoreflect.FileDescriptor

const file_pkg_pb_inventory_proto_rawDesc = "" +
	"\n" +
	"\x16pkg/pb/inventory.proto\x12\tinventory\"\x0e\n" +
	"\fEmptyRequest\"@\n" +
	"\x12FindRecordsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"I\n" +
	"\x11InventoryResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"M\n" +
	"\x13FindRecordsResponse\x126\n" +
	"\arecords\x18\x01 \x03(\v2\x1c.inventory.InventoryResponseR\arecords2a\n" +
	"\x15InventoryProtoService\x12H\n" +
	"\vfindRecords\x12\x17.inventory.EmptyRequest\x1a\x1e.inventory.FindRecordsResponse\"\x00B\n" +
	"Z\b./pkg/pbb\x06proto3"

var (
	file_pkg_pb_inventory_proto_rawDescOnce sync.Once
	file_pkg_pb_inventory_proto_rawDescData []byte
)

func file_pkg_pb_inventory_proto_rawDescGZIP() []byte {
	file_pkg_pb_inventory_proto_rawDescOnce.Do(func() {
		file_pkg_pb_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_pb_inventory_proto_rawDesc), len(file_pkg_pb_inventory_proto_rawDesc)))
	})
	return file_pkg_pb_inventory_proto_rawDescData
}

var file_pkg_pb_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_pb_inventory_proto_goTypes = []any{
	(*EmptyRequest)(nil),        // 0: inventory.EmptyRequest
	(*FindRecordsRequest)(nil),  // 1: inventory.FindRecordsRequest
	(*InventoryResponse)(nil),   // 2: inventory.InventoryResponse
	(*FindRecordsResponse)(nil), // 3: inventory.FindRecordsResponse
}
var file_pkg_pb_inventory_proto_depIdxs = []int32{
	2, // 0: inventory.FindRecordsResponse.records:type_name -> inventory.InventoryResponse
	0, // 1: inventory.InventoryProtoService.findRecords:input_type -> inventory.EmptyRequest
	3, // 2: inventory.InventoryProtoService.findRecords:output_type -> inventory.FindRecordsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_pb_inventory_proto_init() }
func file_pkg_pb_inventory_proto_init() {
	if File_pkg_pb_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_pb_inventory_proto_rawDesc), len(file_pkg_pb_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_pb_inventory_proto_goTypes,
		DependencyIndexes: file_pkg_pb_inventory_proto_depIdxs,
		MessageInfos:      file_pkg_pb_inventory_proto_msgTypes,
	}.Build()
	File_pkg_pb_inventory_proto = out.File
	file_pkg_pb_inventory_proto_goTypes = nil
	file_pkg_pb_inventory_proto_depIdxs = nil
}
